import time
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class FunctionCall(BaseModel):
    """Represents a function call within a tool call."""
    name: Optional[str] = None
    arguments: Optional[str] = None


class ToolCall(BaseModel):
    """Represents a tool call generated by the model."""
    index: int
    id: Optional[str] = None
    type: Optional[str] = "function"
    function: FunctionCall


# --- Pydantic Models ---


class ChatCompletionMessage(BaseModel):
    """Represents a single message in a chat completion conversation."""
    role: str
    content: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None


class ChatCompletionChoice(BaseModel):
    """Represents a single choice in a chat completion response."""
    index: int
    message: ChatCompletionMessage
    finish_reason: Optional[str] = None


class ChatCompletionResponse(BaseModel):
    """Represents the response from a chat completion request."""
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[ChatCompletionChoice]
    usage: Dict[str, Any]


class ChatCompletionChunkDelta(BaseModel):
    """Represents the delta of a message in a streaming response."""
    content: Optional[str] = None
    # Added for DeepSeek-R1 style native reasoning
    reasoning_content: Optional[str] = None
    role: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None


class ChatCompletionChunkChoice(BaseModel):
    """Represents a choice in a streaming chunk."""
    index: int
    delta: ChatCompletionChunkDelta
    finish_reason: Optional[str] = Field(None)


class ChatCompletionChunk(BaseModel):
    """Represents a streaming chunk of a chat completion response."""
    id: str
    object: str = "chat.completion.chunk"
    created: int
    model: str
    choices: List[ChatCompletionChunkChoice]


class ChatCompletionRequest(BaseModel):
    """Represents a request for chat completion."""
    model: str
    messages: List[Dict[str, Any]]
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    max_tokens: Optional[int] = None
    response_format: Optional[Dict[str, str]] = None
    tools: Optional[List[Dict[str, Any]]] = None
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None
    stream: Optional[bool] = False


class EmbeddingRequest(BaseModel):
    """Represents a request for generating embeddings."""
    input: Union[str, List[str]]
    model: str


class EmbeddingResponse(BaseModel):
    """Represents the response from an embedding request."""
    object: str = "list"
    data: List[Dict[str, Any]]
    model: str
    usage: Dict[str, Any]


class TranscriptionModel(BaseModel):
    """Represents the model used for transcription."""
    model: str


class TranscriptionResponse(BaseModel):
    """Represents the response from a transcription request."""
    text: str


class SpeechCreationRequest(BaseModel):
    """Represents a request for speech generation (TTS)."""
    model: str
    input: str
    voice: Optional[str] = "alloy"
    response_format: Optional[str] = "mp3"
    speed: Optional[float] = 1.0


class ReactRequest(BaseModel):
    """Represents a request specifically for the ReAct engine."""
    user_query: str
    model_alias: str
    reasoning_mode: Optional[str] = None
    session_id: Optional[str] = None
    client_system_instruction: Optional[str] = None
    client_manifests: Optional[List[str]] = None
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    max_tokens: Optional[int] = None


class ModelCard(BaseModel):
    """Represents information about a specific model."""
    id: str
    object: str = "model"
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = "magic-proxy"


class ModelList(BaseModel):
    """Represents a list of available models."""
    object: str = "list"
    data: List[ModelCard]


class User(BaseModel):
    """Represents a system user."""
    id: str
    username: str
    token: str  # The API key for this user
    created_at: int
    provider_keys: Dict[str, str] = Field(default_factory=dict)
    config_overrides: Dict[str, Any] = Field(default_factory=dict)
    is_active: bool = True


class UserCreate(BaseModel):
    """Represents a payload for creating a new user."""
    username: str
